CREATE DATABASE RecursosHumanos

USE RecursosHumanos

CREATE TABLE EMPLEADOS(
Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
Cedula VARCHAR(20) NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Apellido VARCHAR(50) NOT NULL,
Telefono VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
Id_Departamento INT FOREIGN KEY REFERENCES DEPARTAMENTOS(Id_Dep),
Id_Cargo INT FOREIGN KEY REFERENCES CARGOS(Id_Car),
[Fecha De Ingreso] DATE NOT NULL,
Salario INT NOT NULL
)

CREATE TABLE NOMINAS(
Id_Nominas INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
Mes INT NOT NULL,
Año INT NOT NULL,
Monto INT NOT NULL
)

CREATE TABLE DEPARTAMENTOS(
Id_Dep INT PRIMARY KEY IDENTITY (1,1),
Departamento VARCHAR(50) NOT NULL,
)

CREATE TABLE CARGOS(
Id_Car INT PRIMARY KEY IDENTITY (1,1),
Cargo VARCHAR(50) NOT NULL
)

SELECT * FROM EMPLEADOS
select * from NOMINAS
select * from DEPARTAMENTOS
select * from CARGOS

-- ELIMINAR

DROP TABLE EMPLEADOS
DROP TABLE DEPARTAMENTOS
DROP TABLE NOMINAS
DROP TABLE CARGOS